// The file is auto-generate by processorTool,do not modify!
package org.lzh.framework.courier.dispatcher;

import org.lzh.framework.courier.ParentActivity;

import java.io.Serializable;

/**
 * This class is generated by annotation @Params */
public class ParentActivityDispatcher<T extends ParentActivityDispatcher> {
  /**
   * The tag to pass data */
  private static final String TAG = ParentActivity.class.getCanonicalName();

  /**
   * The instance of RequestData that is the container of whole filed */
  private ArgsData data;

  private int requestCode = -1;

  protected ParentActivityDispatcher() {
    this.data = new ArgsData();
  }

  /**
   * receive passed data,get data from intent by tag : TAG */
  public static <T extends Serializable> T getArguments(android.content.Intent data) {
    if (data == null || data.getSerializableExtra(TAG) == null) {
      return (T) new ArgsData();
    }
    else {
      return (T) data.getSerializableExtra(TAG);
    }
  }

  public static ParentActivityDispatcher create() {
    ParentActivityDispatcher instance = new ParentActivityDispatcher();
    return instance;
  }

  public T setUsername(String username) {
    this.data.setUsername(username);
    return (T) this;
  }

  /**
   * Set request code,use -1 if not defined */
  public T requestCode(int requestCode) {
    this.requestCode = requestCode;
    return (T) this;
  }

  /**
   * Create intent,put the instance of RequestData into it,and parent class request data */
  public android.content.Intent createIntent(android.content.Context context) {
    android.content.Intent intent = new android.content.Intent(context,ParentActivity.class);
    intent.putExtra(TAG,data);
    return intent;
  }

  /**
   * inner class RequestData,contains all of the field define by annotation @Field */
  public static class ArgsData implements Serializable {
    private String username;

    public ArgsData setUsername(String username) {
      this.username = username;
      return this;
    }

    public String getUsername() {
      return this.username;
    }
  }
}
