// The file is auto-generate by processorTool,do not modify!
package org.lzh.framework.courier.dispatcher;

import org.lzh.framework.courier.SubActivity;

import java.io.Serializable;

/**
 * This class is generated by annotation @Params */
public class SubActivityDispatcher<T extends SubActivityDispatcher> extends ParentActivityDispatcher<T>{
  /**
   * The tag to pass data */
  private static final String TAG = SubActivity.class.getCanonicalName();

  /**
   * The instance of RequestData that is the container of whole filed */
  private ArgsData data;

  private int requestCode = -1;

  private SubActivityDispatcher() {
    this.data = new ArgsData();
  }

  /**
   * receive passed data,get data from intent by tag : TAG */
  public static <T extends Serializable> T getArguments(android.content.Intent data) {
    if (data == null || data.getSerializableExtra(TAG) == null) {
      return (T) new ArgsData();
    }
    else {
      return (T) data.getSerializableExtra(TAG);
    }
  }

  public static SubActivityDispatcher create() {
    SubActivityDispatcher instance = new SubActivityDispatcher();
    return instance;
  }

  public T setPassword(String password) {
    this.data.setPassword(password);
    return (T) this;
  }

  /**
   * Set request code,use -1 if not defined */
  public T requestCode(int requestCode) {
    this.requestCode = requestCode;
    return (T) this;
  }

  /**
   * Create intent,put the instance of RequestData into it,and parent class request data */
  public android.content.Intent createIntent(android.content.Context context) {
    android.content.Intent intent = new android.content.Intent(context,SubActivity.class);
    android.content.Intent parentIntent = super.createIntent(context);
    intent.putExtras(parentIntent);
    intent.putExtra(TAG,data);
    return intent;
  }

  /**
   * launcher a Activity by android.app.Activity */
  public SubActivityDispatcher start(android.app.Activity target) {
    android.content.Intent intent = createIntent(target);
    target.startActivityForResult(intent,requestCode);
    return this;
  }

  /**
   * launcher a Activity by android.app.Fragment */
  public SubActivityDispatcher start(android.app.Fragment target) {
    android.content.Intent intent = createIntent(target.getActivity());
    target.startActivityForResult(intent,requestCode);
    return this;
  }

  /**
   * launcher a Activity by android.support.v4.app.Fragment */
  public SubActivityDispatcher start(android.support.v4.app.Fragment target) {
    android.content.Intent intent = createIntent(target.getActivity());
    target.startActivityForResult(intent,requestCode);
    return this;
  }

  /**
   * inner class RequestData,contains all of the field define by annotation @Field */
  public static class ArgsData implements Serializable {
    private String password;

    public ArgsData setPassword(String password) {
      this.password = password;
      return this;
    }

    public String getPassword() {
      return this.password;
    }
  }
}
